[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Neekko001/PetCrib/blob/main/notebook.ipynb) [![Open in Kaggle](https://kaggle.com/static/images/open-in-kaggle.svg)](https://kaggle.com/kernels/welcome?src=https://github.com/vicradon/ml-workspace/blob/main/shape_detection/notebook.ipynb)

In [11]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import torch
from torch import optim
from torch import nn
from torch.utils.data import DataLoader
from tqdm import tqdm

In [21]:
import json
from itertools import islice

with open("./annotations/instances.json", "r") as annotation_data:
    content = annotation_data.read()
    
annotation_data = json.loads(content)

categories = pd.DataFrame(annotation_data["categories"])
images = pd.DataFrame(annotation_data["images"])
annotations = pd.DataFrame(annotation_data["annotations"])

In [22]:
categories

   id           name supercategory
0   1       triangle         shape
1   2  quadrilateral         shape
2   3       pentagon         shape
3   4        hexagon         shape
4   5       heptagon         shape
5   6        octagon         shape
6   7        decagon         shape

In [23]:
images

      id                 file_name  width  height
0      1  images/triangle_0000.png    250     250
1      2  images/triangle_0001.png    250     250
2      3  images/triangle_0002.png    250     250
3      4  images/triangle_0003.png    250     250
4      5  images/triangle_0004.png    250     250
..   ...                       ...    ...     ...
695  696   images/decagon_0095.png    250     250
696  697   images/decagon_0096.png    250     250
697  698   images/decagon_0097.png    250     250
698  699   images/decagon_0098.png    250     250
699  700   images/decagon_0099.png    250     250

[700 rows x 4 columns]

In [24]:
annotations

,id,image_id,category_id,bbox,area,iscrowd
0,1,1,1,"[44.48, 77.82, 152.93, 134.18]",20520.50,0
1,2,2,1,"[76.3, 67.28, 124.92, 142.51]",17802.77,0
2,3,3,1,"[68.72, 58.87, 109.06, 119.9]",13076.84,0
3,4,4,1,"[55.54, 97.3, 85.9, 80.68]",6930.61,0
4,5,5,1,"[33.28, 57.68, 132.92, 142.95]",19000.85,0
...,...,...,...,...,...,...
695,696,696,7,"[62.28, 96.25, 91.09, 92.82]",8454.98,0
696,697,697,7,"[33.59, 46.54, 116.96, 122.57]",14335.98,0
697,698,698,7,"[67.93, 45.29, 125.52, 131.72]",16533.61,0
698,699,699,7,"[48.39, 44.36, 112.07, 114.22]",12800.42,0
699,700,700,7,"[39.85, 72.52, 111.05, 115.28]",12801.34,0